require 'pry'
require 'nokogiri'
require 'open-uri'

require_relative '../lib/atlas_obscura_cli_app.rb'
require_relative '../lib/atlas_obscura_cli_app/version.rb'
require_relative '../lib/atlas_obscura_cli_app/cli.rb'
require_relative '../lib/continent.rb'
require_relative '../lib/country.rb'
require_relative '../lib/destination.rb'
# require_relative '../lib/'
# require_relative '../lib/'